# Generated by Django 3.2.25 on 2026-09-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemap', '0046_auto_20170907_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='itree_region_default',
            field=models.CharField(blank=True, choices=[('CaNCCoJBK', 'Northern California Coast'), ('CenFlaXXX', 'Central Florida'), ('GulfCoCHS', 'Coastal Plain'), ('InlEmpCLM', 'Inland Empire'), ('InlValMOD', 'Inland Valleys'), ('InterWABQ', 'Interior West'), ('LoMidWXXX', 'Lower Midwest'), ('MidWstMSP', 'Midwest'), ('NMtnPrFNL', 'North'), ('NoEastXXX', 'Northeast'), ('PacfNWLOG', 'Pacific Northwest'), ('PiedmtCLT', 'South'), ('SoCalCSMA', 'Southern California Coast'), ('SWDsrtGDL', 'Southwest Desert'), ('TpIntWBOI', 'Temperate Interior West'), ('TropicPacXXX', 'Tropical')], max_length=20, null=True),
        ),
    ]
