# Generated by Django 3.2.25 on 2026-09-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Something went wrong with your export.'), (0, 'Pending'), (1, 'Query returned no trees or planting sites.'), (2, 'User has no permissions on this model'), (3, 'Ready')], default=0),
        ),
    ]
